# Specify to use the latest Ubuntu
FROM ubuntu:latest

# APT (Advanced Package Tool) update
RUN apt-get update

# Upgrade packages currently installed
RUN apt-get upgrade -y

# Use CMD prompt to echo text on start-up
CMD echo "Hello, World!"