version: '3'
services:
  front-end:
  # Tells compose to look for Dockerfiles in specific directory
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: softy-pinko-front-end:task5
   
  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: soft-pinko-back-end:task5
    depends_on:
      - front-end
  
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: soft-pinko-proxy:task5
    ports:
      - "80:80"
    depends_on:
      - front-end
      - back-end


